output_dir: ./output3  # Directory to save the output files
resume_output: True # False
csv_save: True
experiment_templates:
  - name: My experiment
    # seed: [0, 1, 2]
    device: cpu
    model:
       - name: GCN
      #  - what: What
      # wtf: 0.1
      # params:
      #   hidden_channels: [32]
      #   wtf: [0.1]
       - name: GAT
        #  watas: What
         params:
          hidden_channels: [64, 128]
      
    dataset:
      - name: Cora
        root: ./datasets
        make_undirected: 1
        # what: What
        # transforms:
        # - name: NormalizeFeatures
        #   params:
        #     norm_type: GCN
        # - name: NormalizeAdj
        #   params:
        #     norm_type: GCN
      # - name: Citeseer
      #   root: ./datasets
      #   make_undirected: False
        transforms:
        - name: NormalizeFeatures
          # params:
          #   norm_type: GCN
      #   - name: NormalizeAdj
      #     params:
      #       norm_type: GCN

    attack:
      - scope: local
        name: localDICE
        type: poison
        epsilon: [0.5]
        nodes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
        # min_node_degree: 3
        # topk: 10
    training:
      - max_epochs: 300
        patience: 100
    
    optimizer:
      name: adam
      # what: What
      params:
        lr: 0.01
        weight_decay: 0.0005
        # wtf: [0.1]

    loss:
       - name: CE
       - name: MSE
    
    # wtf:
    #   - 0.1
    #   - 0.2
    #   - 0.3

  # - name: GAT Robustness Experiment
  #   seed: [0, 1]
  #   device: cuda

  #   model:
  #     name: GAT
  #     params:
  #       hidden_channels: [64, 128]
    
  #   dataset:
  #     name: cora
  #     path: ./datasets

  #   attack:
  #     scope: global
  #     name: localDICE
  #     type: poison
  #     epsilon: [0.5]

  #   training:
  #     max_epochs: [400]
  #     patience: 100
    
  #   optimizer:
  #     name: adam
  #     params:
  #       lr: [0.01]
  #       weight_decay: [0.0005]

  #   loss:
  #     name: CE
  
  
  