output_dir: ./output2  # Directory to save the output files
experiment_templates:
  - name: Vanilla GCN against DICE
    seed: [0]
    device: cuda

    model:
      name: GCN
      params:
        hidden_channels: [32]
    
    dataset:
      name: [cora]
      path: ./datasets

    attack:
      scope: local
      name: localDICE
      type: poison
      epsilon: [0.5]
      nodes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
      min_node_degree: 3
      topk: 10
      params:
        make_undirected: False

    evaluation:
      metrics: ['accuracy']

    training:
      max_epochs: [300]
      patience: 100
    
    optimizer:
      name: Adam
      params:
        lr: [0.01]
        weight_decay: [0.0005]
    

  # - name: GAT Robustness Experiment
  #   seed: [0, 1]
  #   device: cuda

  #   model:
  #     name: GAT
  #     params:
  #       hidden_channels: [64, 128]
    
  #   dataset:
  #     name: cora
  #     path: ./datasets

  #   attack:
  #     name: DICE
  #     attack_type: poison
  #     epsilon: [0.05, 0.1, 0.2]

  #   evaluation:
  #     metrics: ['accuracy']

  #   training:
  #     max_epochs: 300
  #     lr: 0.001
  #     weight_decay: 0.0005
  #     patience: 300
  
  
  