output_dir: ./output8
# resume_output: False
# csv_save: True
# esd: True
experiment_templates:
  - name: Local attack_3
    seed: [0]
    device: cuda
    model:
      - name: GCN
        params:
          hidden_channels: 64
    dataset:
      name: [QM9] # ogbn-arxiv 
      root: ./datasets
      make_undirected: true
      # transforms:
      #   - name: ToUndirected
      #   - name: NormalizeFeatures
        # - name: Constant
        #   params:
        #     value: 0.8

    attack:
      - scope: 'global'
        name: DICE
        type: evasion
        epsilon: [0.5]
      # - scope: global
      #   name: FGSM
      #   type: poison
      #   epsilon: [0.5]
      # - scope: global
      #   name: PGD
      #   type: poison
      #   epsilon: [0.5]

      # - scope: local
      #   name: [LocalDICE]
      #   type: evasion
      #   epsilon: [0.6]
      #   nodes_topk: 10
      #   min_node_degree: 2

        # params:
        #   block_size: 100000
      # - scope: local
      #   name: [LocalPRBCD, LocalDICE]
      #   type: [poison, evasion]
      #   epsilon: [0.3]
      #   nodes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
      # - scope: local
      #   name: Nettack
      #   type: evasion
      #   epsilon: [0.2]
      #   nodes: [0]


    training:
      max_epochs: 100
      patience: 70
    
    optimizer:
      name: adam
      params:
        lr: 0.01
        weight_decay: 0.0005

    loss:
      name: CE
    
  # - name: Another Experiment
  #   seed: [0, 1]
  #   device: cuda

  #   model:
  #     name: GAT
  #     params:
  #       hidden_channels: [64, 128]
    
  #   dataset:
  #     name: cora
  #     root: ./datasets
  #     make_undirected: True

  #   attack:
  #     - scope: global
  #       name: DICE
  #       type: poison
  #       epsilon: [0.2, 0.3]
  #     - scope: local
  #       name: localDICE
  #       type: evasion
  #       epsilon: [0.05, 0.1, 0.2]
  #       nodes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

  #   training:
  #     max_epochs: 400
  #     patience: 200
    
  #   optimizer:
  #     name: adam
  #     params:
  #       lr: [0.01]
  #       weight_decay: [0.0005]

  #   loss:
  #     name: CE
  
  
  