output_dir: ./outputs
resume_output: True
csv_save: True
experiment_templates:
  - name: experiments
    seed: [0, 1, 2]
    device: cuda
    model:
      - name: [GPRGNN, GCN_DPR, AirGNN]
        params:
          hidden_channels: 64
    dataset:
      name: [Cora, CS]
      root: ./datasets
      make_undirected: false
      transforms:
        - name: NormalizeFeatures
        - name: Constant
          params:
            value: 0.8
    attack:
      - scope: global
        name: [PRBCD, GRBCD, DICE]
        type: poison
        epsilon: [0.1, 0.2]
    training:
      max_epochs: 100
      patience: 80
    optimizer:
      name: [Adam, SGD]
      params:
        lr: 0.01
        weight_decay: 0.0005
    loss:
      name: CE