output_dir: output_demo
cache_dir: cache_demo
experiment_templates:
  - name: Cora_Global_Poisoning
    seed: 0
    device: cuda
    model:
      - name: [GCN_DPR, myCustomGCN]
        params:
          hidden_channels: 32
      - name: GCN
        params:
          hidden_channels: 64
    dataset:
      name: Cora
      transforms:
        - name: Constant
          params:
            value: 0.1
    attack:
      scope: global
      type: poison
      name: [PRBCD, GRBCD]
      epsilon: 0.1  
    training:
      max_epochs: 100
      patience: 80
    optimizer:
      name: Adam
      params:
        lr: 0.01
        weight_decay: 0.0005
    loss:
      name: CE