channels:
- conda-forge
dependencies:
- python=3.10.13
- pip<=23.3.1
- pip:
  - mlflow==2.12.1
  - cloudpickle==3.0.0
  - jinja2==3.1.2
  - matplotlib==3.8.3
  - numba==0.59.0
  - numpy==1.26.4
  - packaging==21.3
  - pandas==2.2.1
  - pytorch-lightning==2.2.1
  - pyyaml==6.0.1
  - scipy==1.12.0
  - torch-cluster==1.6.3
  - torch-geometric==2.5.0
  - torch-scatter==2.1.2
  - torch-sparse==0.6.18
  - torch-spline-conv==1.2.2
  - torch==2.2.1
name: mlflow-env
